### ISSUE TITLE
Managing OS Projects on Github - 01

### ISSUE THREAD

**Issue by zRich** [lfapac-open-source-evangelist/translation#226]

**Comment by ZoomQuiet** [comment]
> Abstract

部分?

**Comment by ZoomQuiet** [comment]
@zRich [#226 包含原文整理后再次提交 by ZoomQuiet · Pull Request #238 · lfapac-open-source-evangelist/translation](https://github.com/lfapac-open-source-evangelist/translation/tree/DAMA%23226-2)

整理后再次提请
