### ISSUE TITLE
《Technical Debt and Open Source Development》 翻译

### ISSUE THREAD

**Issue by lijiangsheng1** [lfapac-open-source-evangelist/translation#3]

**Comment by lijiangsheng1** [comment]
源文件在此～ 欢迎领域具体的章节。

[TechnicalDebtandOpenSourceDevelopment_Whitepaper_V3.pdf](https://github.com/lfapac-open-source-evangelist/translation/files/9266724/TechnicalDebtandOpenSourceDevelopment_Whitepaper_V3.pdf)

**Comment by lijiangsheng1** [comment]
目录见：

https://github.com/lfapac-open-source-evangelist/translation/tree/main/technical-debt-and-open-source-development

**Comment by JayFrank** [comment]
领取相关章节如下：
Addressing Technical Debt at Scale
Too late! Technical debt is already here. What should we do?
Recommended Practices

**Comment by JuliaZhou2022** [comment]
认领章节：
Working with Technical Debt
Example 1: The Role of Custom Build Systems
Example 2: User Interface Framework
The Role of Upstream Development

**Comment by winterpi** [comment]
点赞，各位好神速，已经没可以认领的章节了，下次参与吧

**Comment by lijiangsheng1** [comment]
> 点赞，各位好神速，已经没可以认领的章节了，下次参与吧

我们还需要校对～ 还望踊跃参与～

**Comment by lijiangsheng1** [comment]
> 领取相关章节如下： Addressing Technical Debt at Scale Too late! Technical debt is already here. What should we do? Recommended Practices

已更新到[contributor.md](https://github.com/lfapac-open-source-evangelist/translation/blob/main/technical-debt-and-open-source-development/contributor.md)

**Comment by lijiangsheng1** [comment]
> 认领章节： Working with Technical Debt Example 1: The Role of Custom Build Systems Example 2: User Interface Framework The Role of Upstream Development

已更新到[contributor.md](https://github.com/lfapac-open-source-evangelist/translation/blob/main/technical-debt-and-open-source-development/contributor.md)

**Comment by JuliaZhou2022** [comment]
> 认领章节： Working with Technical Debt Example 1: The Role of Custom Build Systems Example 2: User Interface Framework The Role of Upstream Development

已完成，[PR#22](https://github.com/lfapac-open-source-evangelist/translation/pull/22)。
