### ISSUE TITLE
final review for Managing Open Source Projects on GitHub

### ISSUE THREAD

**Issue by zRich** [lfapac-open-source-evangelist/translation#390]
veview this one file which contents all

https://github.com/lfapac-open-source-evangelist/translation/blob/main/manageing-os-projects-on-github/content.md

**Comment by wjsvec** [comment]
![image](https://github.com/lfapac-open-source-evangelist/translation/assets/39830125/e63ca71c-b094-4281-84b2-7f63cba71953)
![image](https://github.com/lfapac-open-source-evangelist/translation/assets/39830125/f6f1b37b-8400-4679-b461-256d802b57ce)

中英文之间是否需要空格好像没有统一欸，没有关系吗☺️

**Comment by zRich** [comment]
> ![image](https://private-user-images.githubusercontent.com/39830125/306624325-e63ca71c-b094-4281-84b2-7f63cba71953.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1MTk1NzAsIm5iZiI6MTcwODUxOTI3MCwicGF0aCI6Ii8zOTgzMDEyNS8zMDY2MjQzMjUtZTYzY2E3MWMtYjA5NC00MjgxLTg0YjItN2Y2M2NiYTcxOTUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIxVDEyNDExMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNiYTkyMjA4Y2NhMTQ3ZTdmNjBkMWFiMWQzZTAyMGU3MTVkMTY0OTU5ODk1YTdhYzMwOTJmMzAxZjUyZjkyYTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hQzLrnD-h_4i2uwqwxoY-13e3HfGiZg7zmEOTsajuRs) ![image](https://private-user-images.githubusercontent.com/39830125/306624650-f6f1b37b-8400-4679-b461-256d802b57ce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1MTk1NzAsIm5iZiI6MTcwODUxOTI3MCwicGF0aCI6Ii8zOTgzMDEyNS8zMDY2MjQ2NTAtZjZmMWIzN2ItODQwMC00Njc5LWI0NjEtMjU2ZDgwMmI1N2NlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIxVDEyNDExMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA0YWNhZTQwZmEzNzcxNGM3Zjk5ZTllZjQ0YjU2Yzk0ZmZjOWExMThhNDcwNDE1ZmYzNjQxMzhlNTM0YWYxNTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4Q6tAbOAhmx-Njh7kt8KfSSm3-SOfd2-BIo0Hg3PgK4)
> 
> 中英文之间是否需要空格好像没有统一欸，没有关系吗☺️

我们的习惯是英文在上，中文在下，并且用空行隔开。 （MD格式，不用空行隔开，显示的时候会合并在一行。

**Comment by wjsvec** [comment]
![1708522964987](https://github.com/lfapac-open-source-evangelist/translation/assets/39830125/0ce65c0f-ed50-44b7-9290-b230ae4f74f6)
这里看起来有一些重复片段？

**Comment by wjsvec** [comment]
![image](https://github.com/lfapac-open-source-evangelist/translation/assets/39830125/b1dd0b5d-ffcd-4776-b631-b972bbbab4df)
翻译的列表编号似乎没有正确的从1开始

**Comment by wjsvec** [comment]
![image](https://github.com/lfapac-open-source-evangelist/translation/assets/39830125/fc095310-2768-4f2f-a31e-7f1170becd61)

 peer review 似乎存在“同侪审查”和“同行评审”两种情况，没有特殊需求，名词的翻译或许可以统一一下方便阅读？

**Comment by JayFrank** [comment]
标题：Recommended Practices for Hosting and Managing Open Source Projects on GitHub，目前翻译的是“在GitHub上托管并管理开源项目的实践推荐”，我觉得应该翻译为“在GitHub上托管并管理开源项目的推荐实践”，其中 Recommended Practices 其实和 Best Practices 最佳实践 应该翻译方式类似，因此 Recommended Practices 是否应该翻译为“推荐实践”？

**Comment by JayFrank** [comment]
![截屏2024-02-26 19 51 44](https://github.com/lfapac-open-source-evangelist/translation/assets/12424395/54a29a3b-4f3e-43a0-b503-6a29e6a489b8)
我觉得这里应该翻译为：通过沟通渠道包括问题跟踪器、反馈平台和社区论坛等管理用户支持。

**Comment by JayFrank** [comment]
![截屏2024-02-26 20 04 05](https://github.com/lfapac-open-source-evangelist/translation/assets/12424395/25cbb0fd-73f4-4b4e-9933-7f8f628a0ef2)
licensing 是否翻译为 许可证？

**Comment by JayFrank** [comment]
文章中中文译文的英文标点和中文标点，混用，建议统一

**Comment by JayFrank** [comment]
<img width="1363" alt="截屏2024-02-18 19 27 32" src="https://github.com/lfapac-open-source-evangelist/translation/assets/12424395/1cc9ebf2-4522-4448-a1fa-35ad2882cb10">
“开源位于技术/社区/商业和个人身份的交处” 是否翻译为“开源位于技术/社区/商业和个人身份的交汇处”更加合适？
此外，末尾应该是句号结尾

**Comment by JayFrank** [comment]
<img width="1020" alt="截屏2024-02-26 21 46 36" src="https://github.com/lfapac-open-source-evangelist/translation/assets/12424395/7cec9e1f-59a6-4527-b4d2-bff9989169c5">
第一句翻译不准确，“在我担任微软开源项目办公室（OSPO）主任期间，该公司从在 GitHub上拥有几百名开发人员和仓库，发展到如今拥有数以万计的开发人员和仓库。” 可能会更好

**Comment by JayFrank** [comment]
<img width="1039" alt="截屏2024-02-26 21 50 03" src="https://github.com/lfapac-open-source-evangelist/translation/assets/12424395/8aac8b60-9292-4fe1-aad9-0570a90ddac0">
成功的开源项目与代码同样重要的是人和社区。通过这篇文章，Ibrahim 运用他在开源领域的丰富经验，为您提供一个起点，让您能够充分利用 GitHub 上的开源项目。遵循这里概述的最佳实践将帮助您在项目周围建立一个安全、健壮且充满活力的社区。GitHub 提供了大部分基础设施，而您提供创新和社区。

上文翻译的 澳门 有点问题...

**Comment by JayFrank** [comment]
整篇文章中 Foreword 前言 部分翻译质量略微粗糙，建议 译者 重新再整体看一下
